# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def reverso(n):
    return str(n[::-1])

n = str(input('Digite um número: ')).strip()
print(f'Reverso: {reverso(n)}')